# Generated by Django 5.0.6 on 2024-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_code',
            field=models.CharField(default=1, max_length=30, verbose_name='Ost-Kategoriya nomi'),
            preserve_default=False,
        ),
    ]
